name: Bug report
description: Report a bug or unexpected behaviour
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as you can, it really helps us find and fix bugs faster.
        #### "Security" bugs
        
        [This is open-source software written by hobbyists](https://gitlab.gnome.org/GNOME/libxml2/-/commit/35d04a0848d8648807672e2ac1ba73ff7bbaee3a), maintained by a single volunteer, badly tested, written in a memory-unsafe language and full of security bugs. It is foolish to use this software to process untrusted data. As such, we treat security issues like any other bug. There is no facility for privately submitting a security report and security reports won't be prioritized.

        With that said, if you think you've found a security bug that affects MicroPython (not just this port), please report it to them in the manner they request and leave us out of it.

        #### Not a bug report?

        * If you have a question \"How Do I ...?\", please post it on [GitHub Discussions](https://github.com/orgs/m68k-micropython/discussions/) instead of here.
        * For feature requests, then please [choose a different issue type](https://github.com/micropython/micropython/issues/new/choose).

        #### Existing issue?

        * Please search for [existing issues](https://github.com/m68k-micropython/micropython/issues) matching this bug before reporting.
  - type: input
    id: hw
    attributes:
      label: Hardware
      description: |
        Which hardware or emulator are you using?
      placeholder: |
        emulated, infinite mac, system 6
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: m86k MicroPython version
      description: |
        To find the version:

        1. Open a serial REPL.
        2. Look at the version number shown
        3. Enter that output here.

        If the issue is about building m68k MicroPython, please provide output of `git describe --dirty` and as much information as possible about the build environment.

        If the version or configuration is modified from the official MicroPython releases or the master branch, please tell us the details of this as well.
      placeholder: |
        MicroPython 20250706.2-4.gff8682c2c7.dirty on 2025-07-07; macplus with m68000
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Reproduction
      description: |
        What steps will reproduce the problem? Please include all details that could be relevant about the environment, configuration, etc.

        If there is Python code to reproduce this issue then please either:
        a. Type it into a code block below ([code block guide](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)), or
        b. Post longer code to a [GitHub gist](https://gist.github.com/), or
        c. Create a sample project on GitHub.

        For build issues, please provide the exact build commands that you ran.
      placeholder: |
        1. Copy paste the code provided below into a new file
        2. Double click the file
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: |
         What did you expect m68k MicroPython to do? If comparing output with CPython or a different MicroPython port/version then please provide that output here.
      placeholder: |
        Expected to print "Hello World".

        Here is the correct output, seen with previous MicroPython version v3.14.159:

        > [...]
  - type: textarea
    id: what-happened
    attributes:
      label: Observed behaviour
      description: |
        What actually happened? Where possible please paste exact output, or the complete build log, etc. Very long output can be linked in a [GitHub gist](https://gist.github.com/).
      placeholder: |
        This unexpected exception appears:

        > [...]
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Is there anything else that might help to resolve this issue?
      value: No, I've provided everything above.
  - type: dropdown
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: |
        Do you agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone?
      options:
        - "Yes, I agree"
      multiple: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve MicroPython.
