blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/orgs/m68k-micropython/discussions
    about: Community discussion about all things m68k MicroPython. This is the best place to start if you have questions about using MicroPython on a mac or getting started with m68k MicroPython development.
  - name: MicroPython Documentation
    url: https://docs.micropython.org/
    about: Documentation for using and working with (upstream) MicroPython and libraries.
