name: Feature request
description: Request a feature or improvement in m68k MicroPython
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        This form is for requesting features or improvements in m68k MicroPython.

        #### Understand that m68k MicroPython is of alpha quality
        
        Many desirable features are missing or incomplete. This project will only be successful if a community of interested folks work together to create useful software.
        
        #### Get feedback first

        Before submitting a new feature idea here, consider starting a discussion on [GitHub Discussions](https://github.com/orgs/m68k-micropython/discussions) to get early feedback from the community.

        #### Not a m68k MicroPython core feature?

        * If it's a feature that would make sense for MicroPython and other MicroPython derivatives, please start upstream with [the original MicroPython project](https://github.com/orgs/micropython/discussions).
        * If you have a question \"How Do I ...?\", please post it on GitHub Discussions instead of here.
        * Could this feature be implemented as a pure Python library? If so, please open the request on the [micropython-lib repository](https://github.com/micropython/micropython-lib/issues) instead.

        #### Existing issue?

        * Please search for [existing issues](https://github.com/m68k-micropython/micropython/issues) before opening a new one.
  - type: textarea
    id: feature
    attributes:
      label: Description
      description: |
        Describe the feature you'd like to see added to m68k MicroPython. What does this feature enable and why is it useful?

        If there is an existing discussion somewhere about this feature, please add a link to it as well.
    validations:
      required: true
  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      description: |
        What is your suggestion for implementing this feature?

        (See also: [How to submit a Pull Request](https://github.com/micropython/micropython/wiki/ContributorGuidelines).)
      options:
        - I hope the m68k MicroPython community will implement this feature
        - I intend to implement this feature and would submit a Pull Request if desirable
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: |
        Do you agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone?
      options:
        - "Yes, I agree"
      multiple: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements for m68k MicroPython.
